// main_23 — TIER 3b: FOREIGN GEOMETRY AND CHAINED BOOLEANS.
//
// Measures the interop axis that has never been isolated: what happens when the operands were
// NOT authored by this kernel.  Everything is scored with the ONE shared harness
// src/v2/v2_verdict.h (v2v::v2_verdict); this file computes no verdict of its own.
//
// The driver is CELL-ORIENTED on purpose: one process invocation does one boolean and prints
// one line, so the shell sweep can wrap every cell in `timeout` and a hang costs one cell
// instead of the run.  "cells attempted vs completed" is therefore countable from the log.
//
//   main_23 probe  <src>                        one verdict line for one operand
//   main_23 rt     <src> <tmp.step>             (d) import -> verdict -> export -> import
//   main_23 cell   <cur|v2> <op> <srcA> <srcB>  (a)(b) one boolean, one verdict line
//   main_23 chain  <cur|v2> <op> <s0> <s1> <s2> <s3>   (c) depth 1..3, our own output re-fed
//
// <src> is  own:<box|sphere|cylinder|cone|torus>   built by THIS kernel (the control), or
//           step:<path>[#i]                        BRep i (default 0) of a STEP file.
// Either form takes an optional  @tx,ty,tz  translation suffix.
// <op> is cut | common | fuse.
//
// Sizes of the own: primitives are chosen in occt_pairs.sh to match the OCCT-authored STEP
// primitives exactly, so the own:/step: rows of the same pair are a true A/B on authorship.

#include "src/brep.h"
#include "src/file_step.h"
#include "src/v2/brep_v2_boolean.h"
#include "src/v2/v2_verdict.h"
#include "src/xform.h"

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

using namespace session_cpp;
using session_cpp::v2v::V2Verdict;
using session_cpp::v2v::v2_verdict;
using session_cpp::v2v::v2_verdict_topology_only;

///////////////////////////////////////////////////////////////////////////////////////////
// sources
///////////////////////////////////////////////////////////////////////////////////////////

static BRep translated(const BRep& b, double tx, double ty, double tz) {
    if (tx == 0.0 && ty == 0.0 && tz == 0.0) return b;
    BRep c = b;
    c.xform = Xform::translation(tx, ty, tz);
    return c.transformed();
}

/// Parse "own:sphere@1,0,0" / "step:/path/f.step#2@0,0,3".  Exits 4 on an unreadable source so
/// a missing file is never silently scored as a failed boolean.
static BRep load_src(const std::string& spec_in) {
    std::string spec = spec_in;
    double tx = 0, ty = 0, tz = 0;
    const size_t at = spec.rfind('@');
    if (at != std::string::npos) {
        std::sscanf(spec.c_str() + at + 1, "%lf,%lf,%lf", &tx, &ty, &tz);
        spec = spec.substr(0, at);
    }
    if (spec.rfind("own:", 0) == 0) {
        const std::string n = spec.substr(4);
        // Sizes match the OCCT-authored STEP primitives generated by occt_pairs.sh.
        // create_box's args are FULL edge lengths, centered at the origin -- MEASURED
        // (create_box(4,4,4) gives volume 64), not the "half-extents" its doc-comment claims.
        if (n == "box")      return translated(BRep::create_box(4, 4, 4), tx, ty, tz);
        if (n == "sphere")   return translated(BRep::create_sphere(2.5), tx, ty, tz);
        if (n == "cylinder") return translated(
            BRep::create_cylinder(1.5, 5.0), tx, ty, tz - 2.5);
        if (n == "cone")     return translated(
            BRep::create_cone(2.0, 5.0), tx, ty, tz - 2.5);
        if (n == "torus")    return translated(BRep::create_torus(2.0, 0.7), tx, ty, tz);
        std::fprintf(stderr, "main_23: unknown own: primitive '%s'\n", n.c_str());
        std::exit(4);
    }
    if (spec.rfind("step:", 0) == 0) {
        std::string path = spec.substr(5);
        int idx = 0;
        const size_t h = path.rfind('#');
        if (h != std::string::npos) { idx = std::atoi(path.c_str() + h + 1); path = path.substr(0, h); }
        std::vector<BRep> bs;
        try { bs = file_step::read_file_step_breps(path); }
        catch (const std::exception& e) {
            std::fprintf(stderr, "main_23: STEP read threw on %s: %s\n", path.c_str(), e.what());
            std::exit(4);
        }
        if (bs.empty() || idx < 0 || idx >= (int)bs.size()) {
            std::fprintf(stderr, "main_23: STEP %s yielded %d breps, wanted #%d\n",
                         path.c_str(), (int)bs.size(), idx);
            std::exit(4);
        }
        return translated(bs[idx], tx, ty, tz);
    }
    std::fprintf(stderr, "main_23: bad source '%s'\n", spec_in.c_str());
    std::exit(4);
}

///////////////////////////////////////////////////////////////////////////////////////////
// reporting — ONE line per cell, key=value, so the sweep can grep it
///////////////////////////////////////////////////////////////////////////////////////////

static void print_v(const char* tag, const std::string& name, const V2Verdict& v, double ms) {
    std::printf("%s name=%s closed=%d faces=%d edges=%d naked=%d nonman=%d seam=%d degen=%d "
                "shells=%d solids=%d resid=%.4g vol=%.10g area=%.10g volok=%d conv=%d ms=%.0f\n",
                tag, name.c_str(), v.closed() ? 1 : 0, v.faces, v.edges, v.naked_real,
                v.nonmanifold, v.seam_edges, v.degenerate, v.shells, v.solids,
                v.closure_residual, v.volume, v.area, v.volume_valid ? 1 : 0,
                v.converged ? 1 : 0, ms);
    std::fflush(stdout);
}

static double now_ms() {
    using namespace std::chrono;
    return duration<double, std::milli>(steady_clock::now().time_since_epoch()).count();
}

static BRep::BooleanOp cur_op(const std::string& op) {
    if (op == "cut")    return BRep::BooleanOp::Difference;
    if (op == "common") return BRep::BooleanOp::Intersection;
    return BRep::BooleanOp::Union;
}
static v2sol::V2Op v2_op(const std::string& op) {
    if (op == "cut")    return v2sol::V2Op::Cut;
    if (op == "common") return v2sol::V2Op::Common;
    return v2sol::V2Op::Fuse;
}

/// Run ONE boolean on ONE kernel.  ok=false means it threw; the caller still prints a line so a
/// throw is counted, never dropped.
static bool run_bool(const std::string& kernel, const std::string& op, const BRep& A,
                     const BRep& B, BRep& out, std::string& err) {
    try {
        if (kernel == "v2") {
            v2sol::V2BooleanOptions o;
            out = v2sol::v2_boolean(A, B, v2_op(op), o, nullptr);
        } else {
            out = A.boolean(B, cur_op(op));
        }
        return true;
    } catch (const std::exception& e) { err = e.what(); return false; }
      catch (...)                     { err = "unknown"; return false; }
}

///////////////////////////////////////////////////////////////////////////////////////////

int main(int argc, char** argv) {
    if (argc < 2) { std::fprintf(stderr, "main_23: no command\n"); return 1; }
    const std::string cmd = argv[1];

    // ---- probe -------------------------------------------------------------------------
    if (cmd == "probe" && argc >= 3) {
        const double t0 = now_ms();
        BRep b = load_src(argv[2]);
        const V2Verdict v = v2_verdict(b);
        print_v("PROBE", argv[2], v, now_ms() - t0);
        std::printf("PROBE_EXTRA name=%s is_solid=%d\n", argv[2], b.is_solid() ? 1 : 0);
        std::fflush(stdout);
        return 0;
    }

    // ---- (d) round-trip identity -------------------------------------------------------
    // import -> verdict -> export -> import -> verdict.  NO boolean anywhere.  If this loses
    // topology or volume, every foreign-operand number below is confounded and says so.
    if (cmd == "rt" && argc >= 4) {
        const std::string src = argv[2], tmp = argv[3];
        double t0 = now_ms();
        BRep b0 = load_src(src);
        const V2Verdict v0 = v2_verdict(b0);
        print_v("RT0", src, v0, now_ms() - t0);
        try { file_step::write_file_step_brep(b0, tmp); }
        catch (const std::exception& e) {
            std::printf("RT_WRITE_THROW name=%s what=%s\n", src.c_str(), e.what());
            std::fflush(stdout);
            return 0;
        }
        t0 = now_ms();
        BRep b1 = load_src("step:" + tmp);
        const V2Verdict v1 = v2_verdict(b1);
        print_v("RT1", src, v1, now_ms() - t0);
        const double dv = (std::fabs(v0.volume) > 1e-12)
                              ? std::fabs(v1.volume - v0.volume) / std::fabs(v0.volume)
                              : std::fabs(v1.volume - v0.volume);
        std::printf("RTDIFF name=%s dfaces=%d dnaked=%d dclosed=%d relvol=%.4g\n", src.c_str(),
                    v1.faces - v0.faces, v1.naked_real - v0.naked_real,
                    (v1.closed() ? 1 : 0) - (v0.closed() ? 1 : 0), dv);
        std::fflush(stdout);
        return 0;
    }

    // ---- (a)(b) one boolean cell -------------------------------------------------------
    if (cmd == "cell" && argc >= 6) {
        const std::string kernel = argv[2], op = argv[3];
        BRep A = load_src(argv[4]);
        BRep B = load_src(argv[5]);
        const V2Verdict va = v2_verdict_topology_only(A);
        const V2Verdict vb = v2_verdict_topology_only(B);
        std::printf("OPERANDS k=%s op=%s A=%s B=%s afaces=%d anaked=%d bfaces=%d bnaked=%d\n",
                    kernel.c_str(), op.c_str(), argv[4], argv[5], va.faces, va.naked_real,
                    vb.faces, vb.naked_real);
        std::fflush(stdout);
        BRep R;
        std::string err;
        const double t0 = now_ms();
        const bool ok = run_bool(kernel, op, A, B, R, err);
        const double ms = now_ms() - t0;
        if (!ok) {
            std::printf("CELL k=%s op=%s A=%s B=%s status=THROW what=%s ms=%.0f\n",
                        kernel.c_str(), op.c_str(), argv[4], argv[5], err.c_str(), ms);
            std::fflush(stdout);
            return 0;
        }
        const V2Verdict v = v2_verdict(R);
        std::printf("CELL k=%s op=%s A=%s B=%s status=%s closed=%d faces=%d naked=%d nonman=%d "
                    "shells=%d solids=%d resid=%.4g vol=%.10g volok=%d conv=%d ms=%.0f\n",
                    kernel.c_str(), op.c_str(), argv[4], argv[5],
                    R.m_faces.empty() ? "EMPTY" : "OK", v.closed() ? 1 : 0, v.faces, v.naked_real,
                    v.nonmanifold, v.shells, v.solids, v.closure_residual, v.volume,
                    v.volume_valid ? 1 : 0, v.converged ? 1 : 0, ms);
        std::fflush(stdout);
        if (argc >= 7 && !R.m_faces.empty()) {
            try { file_step::write_file_step_brep(R, argv[6]); }
            catch (...) { std::printf("CELL_WRITE_THROW out=%s\n", argv[6]); }
        }
        return 0;
    }

    // ---- (c) chained booleans, depth 1..3 ----------------------------------------------
    // R1 = s0 op s1 ; R2 = R1 op s2 ; R3 = R2 op s3.  Our OWN output is the left operand at
    // every step, which is the thing the task asks for.  Stops at the first depth that throws
    // or returns an empty result and says which depth that was.
    if (cmd == "chain" && argc >= 7) {
        const std::string kernel = argv[2], op = argv[3];
        BRep acc = load_src(argv[4]);
        {
            const V2Verdict v = v2_verdict(acc);
            print_v("CH0", argv[4], v, 0);
        }
        int last_ok = 0;
        for (int d = 1; d <= 3 && 4 + d < argc; ++d) {
            BRep B = load_src(argv[4 + d]);
            BRep R;
            std::string err;
            const double t0 = now_ms();
            const bool ok = run_bool(kernel, op, acc, B, R, err);
            const double ms = now_ms() - t0;
            if (!ok) {
                std::printf("CHAIN k=%s op=%s depth=%d status=THROW what=%s ms=%.0f\n",
                            kernel.c_str(), op.c_str(), d, err.c_str(), ms);
                std::fflush(stdout);
                break;
            }
            const V2Verdict v = v2_verdict(R);
            std::printf("CHAIN k=%s op=%s depth=%d status=%s closed=%d faces=%d naked=%d "
                        "nonman=%d shells=%d solids=%d resid=%.4g vol=%.10g volok=%d ms=%.0f\n",
                        kernel.c_str(), op.c_str(), d, R.m_faces.empty() ? "EMPTY" : "OK",
                        v.closed() ? 1 : 0, v.faces, v.naked_real, v.nonmanifold, v.shells,
                        v.solids, v.closure_residual, v.volume, v.volume_valid ? 1 : 0, ms);
            std::fflush(stdout);
            if (R.m_faces.empty()) break;
            if (v.closed()) last_ok = d;
            acc = R;
        }
        std::printf("CHAIN_LAST k=%s op=%s last_closed_depth=%d\n", kernel.c_str(), op.c_str(),
                    last_ok);
        std::fflush(stdout);
        return 0;
    }

    std::fprintf(stderr, "main_23: bad arguments\n");
    return 1;
}
